### ISSUE TITLE
Encontrar tipo de valvula a utilizar

### ISSUE THREAD

**Issue by Juan-010** [Juan-010/Sistema-de-preservacion-del-agua#1]
Necesitamos encontrar que tipo de valvula vamos a utilizar en el proyecto. Tiene que ser relativamente económica, y el tipo de pedal depende de si la valvula es digital o analogica.

**Comment by Juan-010** [comment]
https://articulo.mercadolibre.com.ar/MLA-905500219-valvula-solenoide-12v-12-entrada-agua-normal-cerrada-hobb-_JM#position=2&search_layout=stack&type=item&tracking_id=233afc9d-b887-4b62-8eb1-7407b0555a88

**Comment by rossi698** [comment]
https://articulo.mercadolibre.com.ar/MLA-935645846-valvula-solenoide-para-agua-12v-12-pulgadas-emakers-_JM#position=6&search_layout=stack&type=item&tracking_id=c3713a83-f9b3-41f1-ae33-3c9f50d4d774

encontré esa, es la misma, mas barata nada mas

**Comment by rossi698** [comment]
https://articulo.mercadolibre.com.ar/MLA-622774316-electrovalvula-lavarropas-1-via-90-y-180-_JM?attributes=c2FsaWRh%3AMTgwwrA%3D&quantity=1

estas sonde lavarropas, pero funcionan con 220v

**Comment by Juan-010** [comment]
Por cuestiones de seguridad, creo que conviene mas utilizar las de 12V. La que vos decis mas barata seguramente sea la que usemos.
