### ISSUE TITLE
Definir tipo de pedal a utilizar

### ISSUE THREAD

**Issue by Juan-010** [Juan-010/Sistema-de-preservacion-del-agua#2]
Podriamos buscar un pedal de Arduino, todavia no encontre nada acerca de eso. Tambien podemos diseñar un pedal en 3D y armarlo con un pulsador, pero la valvula tendria que ser si o si digital.

**Comment by rossi698** [comment]
En cuanto a pedales podemos utilizar los de las maquinas de coser, pero son costosos, te dejo estos links para que veas a lo qué me refiero.

https://articulo.mercadolibre.com.ar/MLA-850441029-pedal-para-maquina-coser-singer-florencia-_JM

https://articulo.mercadolibre.com.ar/MLA-607306626-pedal-universal-para-maquinas-de-coser-familiares-_JM

**Comment by rossi698** [comment]
Les dejo imagenes del pedal que construí, es de madera y para el contacto utilize dos pedasitos de caño de cobre.

![20210913_092837](https://user-images.githubusercontent.com/90472224/133085377-e41555f8-a342-44ee-bc15-15f6b90e863b.jpg)

![20210911_133122](https://user-images.githubusercontent.com/90472224/133085780-3af6a76d-5fba-48bb-a7ab-06b674e98dfc.jpg)


![20210911_133115](https://user-images.githubusercontent.com/90472224/133085883-6e45e2aa-0fca-4fcf-8c54-53557afc2064.jpg)

**Comment by rossi698** [comment]
https://user-images.githubusercontent.com/90472224/133111042-2a968a3f-564d-417a-95ab-d22fd5a1b1ea.mp4

**Comment by Juan-010** [comment]
Esta muy bueno. Mi idea era usar un pulsador para mandar la señal, en lugar del cobre como hiciste vos. Cuando puedas, pasa un plano de las piezas del pedal, asi lo recreo en 3D para impresion

**Comment by rossi698** [comment]
dale, si el funcionamiento es el mismo de una u otra forma, acá te dejo las piezas con las medidas.
![inferior pedal](https://user-images.githubusercontent.com/90472224/133277466-9a811a2c-a3d0-4bd5-b277-c6a9def2e28a.JPG)
![parte superior pedal](https://user-images.githubusercontent.com/90472224/133277477-5c2afc38-0b8f-4f5b-b18e-3c577ed51af4.JPG)
